website/core/urls.py
from django.urls.conf import path
from django.urls import include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('events/<slug>', views.EventDetail.as_view(), name='event-details'),
    path('events/', views.EventList.as_view(), name='events'),
    path('audio-mixes/', views.AudioList.as_view(), name='audio-mixes'),
    path('video-mixes/', views.VideoList.as_view(), name='video-mixes'),
    path('bio/', views.about, name='bio'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.MyPicsList.as_view(), name='gallery'),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('dashboard/', views.admin, name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls')),
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import reverse

import core.urls
from website import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('s3direct/', include('s3direct.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/axe/models.py
from django.db import models

# Create your models here.

website/core/models.py
from django.db import models
from django.urls import reverse
from polymorphic.models import PolymorphicModel


class MixTape(PolymorphicModel):
    title = models.CharField('Title', max_length=140)
    poster = models.ImageField(upload_to='pics', null=True, blank=True)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField(max_length=500, null=True)
    uploaded = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-uploaded',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return


class Audio(MixTape):
    file = models.FileField(upload_to='audio', null=True)

    class Meta:
        verbose_name_plural = 'Audio'

class Video(MixTape):
    file = models.FileField(upload_to='video', null=True)

    class Meta:
        verbose_name_plural = 'Video'


class MyPics(models.Model):
    file = models.ImageField(upload_to='pics', null=True)
    uploaded = models.DateField(auto_now_add=True)

    def set_as_bio(self):
        About.objects.get(id=1).picture = self


class Gallery(models.Model):
    photo = models.ForeignKey(MyPics, related_name='photos', on_delete=models.DO_NOTHING)


class About(models.Model):
    picture = models.ImageField(upload_to='pics', null=True)
    about = models.TextField()


class Contact(models.Model):
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    phone_2 = models.CharField(max_length=50)
    facebook = models.URLField(null=True, blank=True)
    beatport = models.URLField(null=True, blank=True)
    soundcloud = models.URLField(null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)
    youtube = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)


class Event(models.Model):
    name = models.CharField('Event', max_length=140)
    start = models.DateTimeField()
    end = models.DateTimeField()
    venue = models.CharField(max_length=140)
    slug = models.SlugField(max_length=50, unique=True)
    poster = models.ImageField(upload_to='pics', null=True, blank=True)
    posted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-start',)

    def __str__(self):
        return f'{self.name} ({self.date.strftime("%b %d")})'

    @property
    def admin_slug(self):
        return f'{self.name}-{self.date.strftime("%b-%d")}'

    @property
    def date(self):
        return self.start.date()

    def get_absolute_url(self):
        return reverse('core:event-details', args=[self.slug])

website/core/forms.py
from django import forms
from .models import MyPics


class PhotoForm(forms.ModelForm):
    class Meta:
        model = MyPics
        fields = ('file', )

website/axe/views.py
from django.shortcuts import render

# Create your views here.

website/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, DetailView

from .forms import PhotoForm
from .models import Event, Audio, Video, MixTape, About, MyPics, Contact


class EventList(ListView):
    model = Event


class AudioList(ListView):
    model = Audio


class VideoList(ListView):
    model = Video
    template_name = 'core/audio_list.html'


class AudioDetail(DetailView):
    model = Audio


class EventDetail(DetailView):
    model = Event


def about(request):
    bio = About.objects.get(id=1)
    return render(request,
                  'core/about.html',
                  context={
                      'bio': bio
                  })


def home(request):
    mixes = MixTape.objects.all()[:8]
    events = Event.objects.all()[:4]

    return render(request,
                  'core/home.html',
                  context={
                      'mixes': mixes,
                      'events': events,
                  })


def contact(request):
    return render(request,
                  'core/contact.html',
                  context={'contact': Contact.objects.get(id=1)})


def admin(request):
    audio = Audio.objects.count()
    video = Video.objects.count()
    pics = MyPics.objects.count()
    events = Event.objects.count()

    return render(request,
                  'core/admin.html',
                  context={
                      'audio': audio,
                      'video': video,
                      'pics': pics,
                      'events': events,
                  })


class MyPicsList(ListView):
    model = MyPics


# class FileFieldView(FormView):
#     form_class = FileFieldForm
#     template_name = 'core/upload.html'  # Replace with your template.
#     success_url = '/home/'  # reverse('core:gallery')
#
#     def post(self, request, *args, **kwargs):
#         form = self.get_form()
#         print(form.errors)
#         files = request.FILES.getlist('pics')
#         print(request.FILES)
#         if form.is_valid():
#             print('form_valid')
#             for f in files:
#                 pic = MyPics.objects.create(picture=f)
#                 pic.save()
#             return self.form_valid(form)
#         else:
#             print('form is invalid')
#             return self.form_invalid(form)


class UploadView(View, LoginRequiredMixin):
    def get(self, request):
        photos_list = MyPics.objects.all()
        return render(self.request, 'core/upload.html', {'photos': photos_list})

    def post(self, request):
        form = PhotoForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()
            data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)

website/core/templates/core/about.html
{% extends "base.html" %}

{% block main %}
    <div class="content mt-3 row">
        <div class="col-md-6">
            <img style="max-width: 100%" src="{{ bio.picture.url }}" alt="">
        </div>
        <div class="col-md-6">
            {{ bio.about }}
            <div class="text-center mt-3">
                <a href="{% url "admin:core_about_change" object_id='1' %}" class="btn btn-secondary">Edit Bio</a>
            </div>
        </div>
    </div>
{% endblock %}
{% block active %}
    var id = 'bio';
{% endblock %}

website/core/templates/core/admin.html
{% extends 'base.html' %}
{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card text-center bg-primary text-white mb-3">
                    <div class="card-body">
                        <h3>Audio</h3>
                        <h1 class="display-4">
                            <i class="fa fa-music"></i> {{ audio }}
                        </h1>
                        <a href="{% url "admin:core_audio_add" %}" class="btn btn-outline-light btn-sm">Upload Audio</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card text-center bg-primary text-white mb-3">
                    <div class="card-body">
                        <h3>Video</h3>
                        <h1 class="display-4">
                            <i class="fa fa-file-movie-o"></i> {{ video }}
                        </h1>
                        <a href="{% url "admin:core_video_add" %}" class="btn btn-outline-light btn-sm">Upload Video</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card text-center bg-primary text-white mb-3">
                    <div class="card-body">
                        <h3>Events</h3>
                        <h1 class="display-4">
                            <i class="fa fa-calendar"></i> {{ events }}
                        </h1>
                        <a href="{% url "admin:core_event_add" %}" class="btn btn-outline-light btn-sm">Add Event</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card text-center bg-primary text-white mb-3">
                    <div class="card-body">
                        <h3>Gallery</h3>
                        <h1 class="display-4">
                            <i class="fa fa-picture-o"></i> {{ pics }}
                        </h1>
                        <a href="{% url "core:upload" %}" class="btn btn-outline-light btn-sm">Upload Photos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block active %}
    var id = 'admin';
{% endblock %}

website/core/templates/core/admin/mypics/custom.html
{% extends "admin/change_form.html" %}
{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
<fieldset class="module">
  <h2>Upload Photos</h2>
  <input name="photos_multiple" type="file" multiple />
</fieldset>
{% endblock %}

website/core/templates/core/audio_list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block main %}
    <div class="content mt-3 ml-4">
        {% for audio in object_list %}
            <div class="col-md-3 col-sm-12">
                {% if audio.poster %}
                    {% thumbnail audio.poster "270x270" as im %}
                        <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                {% else %}
                    <img src="/media/cache/0d/1f/0d1f9692f2fc1e31d744cdf09976c212.jpg" alt="">
                {% endif %}
                <p><a href="{{ audio.get_absolute_url }}">{{ audio.title }}</a></p>
                <p><a href="{{ audio.file.url }}" class="btn btn-primary">Download</a></p>
                <p>{{ audio.description }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block active %}
    var id = 'mixes';
{% endblock %}

website/core/templates/core/contact.html
{% extends "base.html" %}
{% block active %}
    var id = 'contact';
{% endblock %}
{% block main %}
    <div class="container">
        <div class="content mt-3">
            <div class="row">
                <div class="col-md-4 mt-5">
                    <div class="contact">
                        <a href="tel:{{ contact.phone }}">
                            <i class="fa fa-phone"></i> {{ contact.phone }}
                        </a>
                    </div>
                    <div class="contact">
                        <a href="tel:{{ contact.phone_2 }}">
                            <i class="fa fa-whatsapp"></i> {{ contact.phone_2 }}
                        </a>
                    </div>
                    <hr>
                    <div class="contact">
                        <a href="mailto:{{ contact.email }}">
                            <i class="fa fa-envelope"></i> <span class="contact-email">{{ contact.email }}</span>
                        </a>
                    </div>
                </div>
                <div class="col-md-8">
                    <h4 class="mb-3">Contact Form</h4>
                    <form class="needs-validation" novalidate="">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="firstName">First name</label>
                                <input class="form-control" id="firstName" placeholder="" value="" required="" type="text">
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="lastName">Last name</label>
                                <input class="form-control" id="lastName" placeholder="" value="" required="" type="text">
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="email">Email <span class="text-muted"></span></label>
                            <input class="form-control" id="email" placeholder="you@example.com" type="email">
                            <div class="invalid-feedback">
                                Please enter a valid email address
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="subject">Subject<span class="text-muted"></span></label>
                            <input class="form-control" id="subject" placeholder="subject" type="text">
                            <div class="invalid-feedback">
                                Please enter a valid subject
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="message">Message</label>
                            <textarea class="form-control" id="message" placeholder="Message" value="" required=""></textarea>
                            <div class="invalid-feedback">
                                Please enter your message
                            </div>
                        </div>
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Send Message</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

website/core/templates/core/event_detail.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block main %}
    <div class="content mt-3">
        {% if event.poster %}
            {% thumbnail event.poster "300x300" as im %}
                <img src="{{ im.url }}" alt="">
            {% endthumbnail %}
        {% else %}
            <img src="/media/cache/e2/00/e2009cd3d4f6ae965e1a5184700eb06a.jpg" alt="">
        {% endif %}
        <p>{{ event.name }}</p>
        <p><i class="fa fa-map-marker"></i> {{ event.venue }}</p>
        <p><i class="fa fa-calendar"></i> {{ event.start.time }} to {{ event.end.time }}</p>
    </div>
{% endblock %}
{% block active %}
    var id = 'events';
{% endblock %}

website/core/templates/core/event_list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block main %}
    <div class="content mt-3 ml-4">
        {% for event in object_list %}
            <div class="col-md-3 col-sm-12">
                {% if event.poster %}
                    {% thumbnail event.poster "270x270" as im %}
                        <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                    {% else %}
                    <img src="/media/cache/e2/00/e2009cd3d4f6ae965e1a5184700eb06a.jpg" alt="">
                {% endif %}
                <p><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></p>
                <p><i class="fa fa-map-marker"></i> {{ event.venue }}</p>
                <p><i class="fa fa-calendar"></i> {{ event.start.date }} {{ event.start.time }} to {{ event.end.time }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block active %}
    var id = 'events';
{% endblock %}

website/core/templates/core/home.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block main %}
    <div id="landing">
        <div id="landing-text">
            <div id="landing-text-inner">
                <h1>DJ Madollar</h1>
                <h2>Madollar the Entertainer</h2>
                <a href="#" class="btn-landing" id="go_to_mix">
                    View Mixtapes
                </a>
            </div>
        </div>
        <div id="landing-image"></div>
    </div>
    <div class="content mt-3 mx-2">
        <div class="card" id="mixtapes">
            <div class="card-header">
                <h4 class="text-center">Mix tapes</h4>
            </div>
            <div class="card-body">
                {% for audio in mixes %}
                    <div class="col-md-3 col-sm-12">
                        <div class="card">
                            {% if audio.poster %}
                                {% thumbnail audio.poster "270x270" as im %}
                                    <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}
                            {% else %}
                                <img src="/media/cache/0d/1f/0d1f9692f2fc1e31d744cdf09976c212.jpg" alt="">
                            {% endif %}
                            <p><a href="{{ audio.get_absolute_url }}">{{ audio.title }}</a></p>
                            <p><a href="{{ audio.file.url }}" class="btn btn-primary">Download</a></p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="card" id="events">
            <div class="card-header">
                <h4 class="text-center">Events</h4>
            </div>
            <div class="card-body">
                {% for event in events %}
                    <div class="col-md-3 col-sm-12">
                        <div class="card">
                            {% if event.poster %}
                                {% thumbnail event.poster "270x270" as im %}
                                    <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}
                            {% else %}
                                <img src="/media/cache/e2/00/e2009cd3d4f6ae965e1a5184700eb06a.jpg" alt="">
                            {% endif %}
                            <p><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></p>
                            <p><i class="fa fa-map-marker"></i> {{ event.venue }}</p>
                            <p><i class="fa fa-calendar"></i> {{ event.start.date }} {{ event.start.time }} to {{ event.end.time }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

website/core/templates/core/mypics_list.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block main %}
    <div class="content mt-3 ml-4">
        {% for pic in object_list %}
            <div class="col-md-3 col-sm-12">
                {% thumbnail pic.file "270x270" as im %}
                    <img src="{{ im.url }}" alt="">
                {% endthumbnail %}
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block active %}
    var id = 'gallery';
{% endblock %}

website/core/templates/core/upload.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block main %}
    {% comment %}    <div class="content mt-3 ml-4">
        <form action="" method="post">
            {{ form | bootstrap }}
            {% csrf_token %}
            <button class="btn btn-primary btn-block mt-1" type="submit" >Upload</button >
        </form>
    </div>{% endcomment %}
    {# 1. BUTTON TO TRIGGER THE ACTION #}
    <div class="container content mt-3">
        <button type="button" class="btn btn-primary js-upload-photos">
            <i class="fa fa-upload"></i> Upload photos
        </button>

        <div class="well text-muted text-center bg-light pt-4 pb-4 mt-3" style="border-radius: 10px;">
            <i class="fa fa-arrow-down" style="font-size: 4rem; "></i>
            <h3>Drop Photos Here to Upload</h3>
        </div>

        {# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
        <input id="fileupload" type="file" name="file" multiple
               style="display: none;"
               data-url="{% url 'core:upload' %}"
               data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

        {# 3. TABLE TO DISPLAY THE UPLOADED PHOTOS #}
        <table id="gallery" class="table table-bordered mt-3">
            <thead>
            <tr>
                <th>Photo</th>
            </tr>
            </thead>
            <tbody>
            {% for photo in photos %}
                <tr>
                    <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Uploading...</h4>
                </div>
                <div class="modal-body">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    {# JQUERY FILE UPLOAD SCRIPTS #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.iframe-transport/1.0.1/jquery.iframe-transport.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary-jquery-file-upload/2.5.0/cloudinary-jquery-file-upload.min.js"></script>

    {# PHOTOS PAGE SCRIPTS #}
    <script src="{% static 'js/basic-upload.js' %}"></script>
{% endblock %}

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DJ Madollar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
</head>
<body onload="active()">
<header class="masthead">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" id="nav">
        <div class="container">
            <a href="{% url 'core:home' %}" class="navbar-brand">DJ Madollar</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav col-md-7" >
                    <li class="nav-item px-2">
                        <a href="{% url 'core:home' %}" class="nav-link" id="home">Home</a>
                    </li>
                    <li class="nav-item px-2">
                        <a href="{% url 'core:bio' %}" class="nav-link" id="bio">Bio</a>
                    </li>
                    <li class="nav-item dropdown px-2">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="mixes">Mixes</a>
                        <div class="dropdown-menu">
                            <a href="{% url 'core:audio-mixes' %}" class="dropdown-item">
                                <i class="fa fa-file-audio-o"></i> Audio
                            </a>
                            <a href="{% url 'core:video-mixes' %}" class="dropdown-item">
                                <i class="fa fa-file-video-o"></i> Videos
                            </a>
                        </div>
                    </li>
                    <li class="nav-item px-2">
                        <a href="{% url 'core:events' %}" class="nav-link" id="events">Events</a>
                    </li>
                    <li class="nav-item px-2">
                        <a href="{% url 'core:gallery' %}" class="nav-link" id="gallery">Gallery</a>
                    </li>
                    <li class="nav-item px-2">
                        <a href="{% url 'core:contact' %}" class="nav-link" id="contact">Contact</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item px-2">
                            <a href="{% url 'core:dashboard' %}" class="nav-link" id="admin">Admin</a>
                        </li>
                    {% endif %}
                </ul>
                <div class="soc" col-md-4>
                    <ul class="navbar-nav social" id="navbarNav">
                        <li class="nav-item px-2">
                            <a href="https://twitter.com/dj_m254" class="nav-link" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li class="nav-item px-2">
                            <a href="http://web.facebook.com/frank.njuguna.984" class="nav-link" target="_blank">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="nav-item px-2">
                            <a href="http://www.youtube.com/channel/UCMNMs-iUbmR6tC3OeqdcWdA" class="nav-link" target="_blank">
                                <i class="fa fa-youtube"></i>
                            </a>
                        </li>
                        <li class="nav-item px-2">
                            <a href="http://instagram.com/dj_m254" class="nav-link" target="_blank">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>

                        <li class="nav-item px-2">
                            <a href="https://plus.google.com/113109581692426188323" class="nav-link" target="_blank">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
    </nav>

</header>

<div class="main">
    <div class="container">
        {% block main %}
            Main Block
        {% endblock %}
    </div>
</div>

<footer class="footer bg-dark text-white mt-3">
    <div class="container text-center">
        <span>2018 &copy; Madollar Entertainment. Designed by <a href="tel:0725926132">Kinyanjui Karanja</a></span>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src={% static "js/ckeditor.js" %}></script>
<script>
    CKEDITOR.replace( 'editor1' );
</script>
<script>
    function active(){
        {% block active %}
            var id = 'home';
        {% endblock %}
        var btn = document.getElementById(id);
        btn.className += " active";}
</script>
<script>
    $('#go_to_mix').on('click', function(){
        const mixes = $('#mixtapes').position().top;

        $('html, body').animate(
            {
                scrollTop: mixes
            },
            900
        );
    });
</script>
{% block javascript %}
{% endblock %}
</body>
</html>

website/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}">
	<title>DJ Madollar | Home</title>
</head>
<body>
	<header>
		<div class="container">
			<nav class="navigation">
				<ul>
					<li>
						<a href="{% url "core:home" %}">Home</a>
					</li>
					<li>
						<a href="about.html">About</a>
					</li>
					<li>
						<a href="mixtapes.html">MixTapes</a>
					</li>
					<li>
						<a href="contact.html">Contact</a>
					</li>
				</ul>
			</nav>
			<nav class="social-media">
				<ul>
					<li>
						<a href="https://www.facebook.com"><img src={% static "img/facebook.png" %}></a>
					</li>
					<li>
						<a href="https://www.beatport.com"><img src={% static "img/beatport.png" %}></a>
					</li>
					<li>
						<a href="https://www.instagram.com"><img src={% static "img/instagram.png" %}></a>
					</li>
				</ul>	
			</nav>
		</div>

	</header>
    <div class="main">
        {% block main %}
            Main Block
        {% endblock %}
    </div>
	<footer>
		<p>DJ Madollar. &copy;2018 <a href="mailto:ekkinyanjui@gmail.com">Website Designer</a></p>
	</footer>
</body>
</html>